function createfigureboat(X1, Y1, X2, X3, Y2)
%CREATEFIGURE(X1,Y1,X2,X3,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 29-Oct-2008 23:53:56

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Visible','off','Parent',figure1,...
    'PlotBoxAspectRatio',[378.2 351.3 87.82],...
    'DataAspectRatio',[1 1 1]);
box('on');
hold('all');

% Create plot
plot(X1,Y1,'LineWidth',4,'Color',[0 0 0]);

% Create plot
plot(X2,X1,'LineStyle','--','Color',[0 0 0]);

% Create text
text('Parent',axes1,'String','L','Position',[5.481 5.277 67.07],...
    'FontSize',14);

% Create text
text('Parent',axes1,'String','A','Position',[-0.5712 0.6236 17.32],...
    'FontSize',14);

% Create text
text('Parent',axes1,'String','B','Position',[-0.5 8 0],'FontSize',14);

% Create text
text('Parent',axes1,'String','T','Position',[-2.5 3 0],'FontSize',14);

% Create text
text('Parent',axes1,'String','O','Position',[-3.8 0.009943 67.07],...
    'FontSize',14);

% Create plot
plot(X3,Y2,'Color',[0 0 0]);

% Create textbox
annotation(figure1,'textbox','String',{'H'},'FontSize',14,...
    'FontName','Times New Roman',...
    'FontAngle','italic',...
    'LineStyle','none',...
    'Position',[0.6434 0.1243 0.05834 0.07657]);

% Create textbox
annotation(figure1,'textbox','String',{'\itb'},'FontSize',14,...
    'FontName','Times New Roman',...
    'LineStyle','none',...
    'Position',[0.7131 0.289 0.05292 0.07657]);

% Create doublearrow
annotation(figure1,'doublearrow',[0.7725 0.7725],[0.2088 0.4501]);

% Create textbox
annotation(figure1,'textbox','String',{'M'},'FontSize',14,...
    'FontName','Times New Roman',...
    'FontAngle','italic',...
    'LineStyle','none',...
    'Position',[0.6107 0.2983 0.06106 0.07657]);

% Create textbox
annotation(figure1,'textbox','String',{'R'},'FontSize',14,...
    'FontName','Times New Roman',...
    'FontAngle','italic',...
    'LineStyle','none',...
    'Position',[0.6311 0.4677 0.05563 0.07657]);

% Create textbox
annotation(figure1,'textbox','String',{'\itV'},'FontSize',14,...
    'FontName','Times New Roman',...
    'LineStyle','none',...
    'Position',[0.4713 0.1011 0.05563 0.07657]);

% Create arrow
annotation(figure1,'arrow',[0.5455 0.5451],[0.09745 0.1949]);

% Create arrow
annotation(figure1,'arrow',[0.5455 0.3935],[0.9165 0.2088]);

% Create arrow
annotation(figure1,'arrow',[0.6142 0.5814],[0.2867 0.2923]);

% Create arrow
annotation(figure1,'arrow',[0.7712 0.5561],[0.2032 0.2042]);

% Create arrow
annotation(figure1,'arrow',[0.5513 0.8566],[0.4491 0.4478]);

% Create doublearrow
annotation(figure1,'doublearrow',[0.8697 0.869],[0.9142 0.1972]);

