SET TRANSACTION ISOLATION LEVEL REPEATABLE READ-- PROBLEM : READ COMMITTED
BEGIN TRAN
	print '1'
	SELECT * FROM Restaurant
	WAITFOR DELAY '00:00:10'
	print '2'
	SELECT * FROM Restaurant
COMMIT TRAN;

select * from Restaurant;

