-- PROBLEM: SET TRANSACTION ISOLATION LEVEL TO REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE --PROBLEM: LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * FROM Meniu
	WAITFOR DELAY '00:00:07'
	SELECT * FROM Meniu
COMMIT TRAN

