SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED -- Problem
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
	SELECT * FROM Publicatii;
	WAITFOR DELAY '00:00:10';
	SELECT * FROM Publicatii;
COMMIT TRAN

SELECT * FROM Publicatii;